version: "3"
services:
  server:
    build: .
    ports:
      - 80:3000
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo:latest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
