export type Option = { value: string, label: string };

export const regions = [
  { value: "Hlavní město Praha", label: "Hlavní město Praha" },
  { value: "Středočeský kraj", label: "Středočeský kraj" },
  { value: "Jihočeský kraj", label: "Jihočeský kraj" },
  { value: "Plzeňský kraj", label: "Plzeňský kraj" },
  { value: "Karlovarský kraj", label: "Karlovarský kraj" },
  { value: "Ústecký kraj", label: "Ústecký kraj" },
  { value: "Liberecký kraj", label: "Liberecký kraj" },
  { value: "Královehradecký kraj", label: "Královehradecký kraj" },
  { value: "Pardubický kraj", label: "Pardubický kraj" },
  { value: "Kraj Vysočina", label: "Kraj Vysočina" },
  { value: "Jihomoravský kraj", label: "Jihomoravský kraj" },
  { value: "Olomoucký kraj", label: "Olomoucký kraj" },
  { value: "Moravskoslezský kraj", label: "Moravskoslezský kraj" },
  { value: "Zlínský kraj", label: "Zlínský kraj" },
];

export const districts = {
  "Hlavní město Praha": [
    { value: "Praha 1", label: "Praha 1" },
    { value: "Praha 2", label: "Praha 2" },
    { value: "Praha 3", label: "Praha 3" },
    { value: "Praha 4", label: "Praha 4" },
    { value: "Praha 5", label: "Praha 5" },
    { value: "Praha 6", label: "Praha 6" },
    { value: "Praha 7", label: "Praha 7" },
    { value: "Praha 8", label: "Praha 8" },
    { value: "Praha 9", label: "Praha 9" },
    { value: "Praha 10", label: "Praha 10" },
  ],
  "Středočeský kraj": [
    { value: "Benešov", label: "Benešov" },
    { value: "Beroun", label: "Beroun" },
    { value: "Kladno", label: "Kladno" },
    { value: "Kolín", label: "Kolín" },
    { value: "Kutná Hora", label: "Kutná Hora" },
    { value: "Mělník", label: "Mělník" },
    { value: "Mladá Boleslav", label: "Mladá Boleslav" },
    { value: "Nymburk", label: "Nymburk" },
    { value: "Praha-východ", label: "Praha-východ" },
    { value: "Praha-západ", label: "Praha-západ" },
    { value: "Příbram", label: "Příbram" },
    { value: "Rakovník", label: "Rakovník" },
  ],
  "Jihočeský kraj": [
    { value: "České Budějovice", label: "České Budějovice" },
    { value: "Český Krumlov", label: "Český Krumlov" },
    { value: "Jindřichův Hradec", label: "Jindřichův Hradec" },
    { value: "Písek", label: "Písek" },
    { value: "Prachatice", label: "Prachatice" },
    { value: "Strakonice", label: "Strakonice" },
    { value: "Tábor", label: "Tábor" },
  ],
  "Plzeňský kraj": [
    { value: "Domažlice", label: "Domažlice" },
    { value: "Klatovy", label: "Klatovy" },
    { value: "Plzeň-město", label: "Plzeň-město" },
    { value: "Plzeň-jih", label: "Plzeň-jih" },
    { value: "Plzeň-sever", label: "Plzeň-sever" },
    { value: "Rokycany", label: "Rokycany" },
    { value: "Tachov", label: "Tachov" },
  ],
  "Karlovarský kraj": [
    { value: "Cheb", label: "Cheb" },
    { value: "Karlovy Vary", label: "Karlovy Vary" },
    { value: "Sokolov", label: "Sokolov" },
  ],
  "Ústecký kraj": [
    { value: "Děčín", label: "Děčín" },
    { value: "Chomutov", label: "Chomutov" },
    { value: "Litoměřice", label: "Litoměřice" },
    { value: "Louny", label: "Louny" },
    { value: "Most", label: "Most" },
    { value: "Teplice", label: "Teplice" },
    { value: "Ústí nad Labem", label: "Ústí nad Labem" },
  ],
  "Liberecký kraj": [
    { value: "Česká Lípa", label: "Česká Lípa" },
    { value: "Jablonec nad Nisou", label: "Jablonec nad Nisou" },
    { value: "Liberec", label: "Liberec" },
    { value: "Semily", label: "Semily" },
  ],
  "Královehradecký kraj": [
    { value: "Hradec Králové", label: "Hradec Králové" },
    { value: "Jičín", label: "Jičín" },
    { value: "Náchod", label: "Náchod" },
    { value: "Rychnov nad Kněžnou", label: "Rychnov nad Kněžnou" },
    { value: "Trutnov", label: "Trutnov" },
  ],
  "Pardubický kraj": [
    { value: "Chrudim", label: "Chrudim" },
    { value: "Pardubice", label: "Pardubice" },
    { value: "Svitavy", label: "Svitavy" },
    { value: "Ústí nad Orlicí", label: "Ústí nad Orlicí" },
  ],
  "Kraj Vysočina": [
    { value: "Havlíčkův Brod", label: "Havlíčkův Brod" },
    { value: "Jihlava", label: "Jihlava" },
    { value: "Pelhřimov", label: "Pelhřimov" },
    { value: "Třebíč", label: "Třebíč" },
    { value: "Žďár nad Sázavou", label: "Žďár nad Sázavou" },
  ],
  "Jihomoravský kraj": [
    { value: "Blansko", label: "Blansko" },
    { value: "Brno-město", label: "Brno-město" },
    { value: "Brno-venkov", label: "Brno-venkov" },
    { value: "Břeclav", label: "Břeclav" },
    { value: "Hodonín", label: "Hodonín" },
    { value: "Vyškov", label: "Vyškov" },
    { value: "Znojmo", label: "Znojmo" },
  ],
  "Olomoucký kraj": [
    { value: "Jeseník", label: "Jeseník" },
    { value: "Olomouc", label: "Olomouc" },
    { value: "Prostějov", label: "Prostějov" },
    { value: "Přerov", label: "Přerov" },
    { value: "Šumperk", label: "Šumperk" },
  ],
  "Moravskoslezský kraj": [
    { value: "Bruntál", label: "Bruntál" },
    { value: "Frýdek-Místek", label: "Frýdek-Místek" },
    { value: "Karviná", label: "Karviná" },
    { value: "Nový Jičín", label: "Nový Jičín" },
    { value: "Opava", label: "Opava" },
    { value: "Ostrava-město", label: "Ostrava-město" },
  ],
  "Zlínský kraj": [
    { value: "Kroměříž", label: "Kroměříž" },
    { value: "Uherské Hradiště", label: "Uherské Hradiště" },
    { value: "Vsetín", label: "Vsetín" },
    { value: "Zlín", label: "Zlín" },
  ],
};
