export const regions = [
  { value: 1, label: "Hlavní město Praha" },
  { value: 2, label: "Středočeský kraj" },
  { value: 3, label: "Jihočeský kraj" },
  { value: 4, label: "Plzeňský kraj" },
  { value: 5, label: "Karlovarský kraj" },
  { value: 6, label: "Ústecký kraj" },
  { value: 7, label: "Liberecký kraj" },
  { value: 8, label: "Královehradecký kraj" },
  { value: 9, label: "Pardubický kraj" },
  { value: 10, label: "Kraj Vysočina" },
  { value: 11, label: "Jihomoravský kraj" },
  { value: 12, label: "Olomouvcký kraj" },
  { value: 13, label: "Moravskoslezský kraj" },
  { value: 14, label: "Zlínský kraj" },
];
